sudo: required
services:
  - docker

before_install:
  - docker build -t noalistic/birdboard-test -f ./deployment/app-dockerfile .

script:
  - docker run -e CI=true noalistic/birdboard-test vendor/bin/phpunit -- --coverage

after_success:
  # build docker images
  - docker build -t noalistic/birdboard-app ./development/app-dockerfile
  - docker build -t noalistic/ninostyle-web ./development/app-dockerfile

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these build images and push to docker hub
  - docker push noalistic/ninostyle-app
  - docker push noalistic/ninostyle-web
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: ninostyle-docker
#   env: NinostyleDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-946065250109
#   bucket_path: docker-ninostyle
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
