sudo: required
services:
  - docker

before_install:
  - docker build -t noalistic/birdboard-test -f Dockerfile .
script:
  - docker run noalistic/birdboard-test vendor/bin/phpunit

after_success:
  - docker build -t noalistic/birdboard-app .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push noalistic/birdboard-app

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: birdboard
  env: Birdboard-env-1
  bucket_name: elasticbeanstalk-us-east-2-946065250109
  bucket_path: birdboard
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
