sudo: required
services:
  - docker

before_install:
  - docker build -t noalistic/birdboard-test -f ./development/app.dockerfile .

script:
  - docker run -e CI=true noalistic/birdboard-test vendor/bin/phpunit tests/Feature/ProjectTasksTest.php

after_success:
  # build docker images
  - docker build -t noalistic/birdboard-app ./development/app.dockerfile
  - docker build -t noalistic/birdboard-web ./development/web.dockerfile
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these build images and push to docker hub
  - docker push noalistic/birdboard-app
  - docker push noalistic/birdboard-web
